### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by JagaRamesh** [malsce/sql-scratch-capstone-turn-in#1]
**Rubric Score**
**Criteria 1: Report**
	* Score Level: 4 (Exceeds Expectations)
	* Comment(s): Excellent presentation.  Accurate Survey analysis and Home-try-on analysis for 3 & 5 pairs. The recommendations are well stated based on data evidence. All questions were answered. Good Job!

**Criteria 2: Query Accuracy**
	* Score Level: 4 (Exceeds Expectations)
	* Comment(s): The queries retrieve the data accurately. 

**Criteria 3: Query Formatting**
	* Score Level: 3 (Meets Expectations)
	* Comment(s): One of the recommendation in SQL Formatting is that "Each column name gets its own line in SELECT clauses". I noticed that this is not followed. Rest of the formatting guidelines are followed.

**Criteria 4: Understanding underlying concepts and terminology**
	* Score Level: 4 (Exceeds Expectations)
	* Comment(s): Good understanding of funnel conversion analysis. The analysis for both funnel analysis are done accurately and recommendations stated were correct.

**Overall Score: 15/16**
Excellent work. Good coding skills. I would suggest to specify each column name in a separate line for readability when writing complex SQL statement. The presentation is well structured, starting with "Table of contents" and ending with recommendations. The analysis and the results are laid out neatly.  The Survey analysis and the Home-try-on analysis were accurate. Well done!

**Comment by malsce** [comment]
Thx :)
